author: Marcin Sas-Szymański
email: sasik520@gmail.com
github_username:  jekyll
url: https://synek317.github.io
title: Inteligentne miasto na 1001 sposobów
description:  (lub trochę mniej)
theme: minima