author: Marcin Sas-Szymański
email: synek317@gmail.com
github_username:  jekyll
url: https://synek317.github.io
title: Simple man devblog
description:
theme: jekyll-theme-slate
disqus:
  shortname: synek317
gems:
  - jekyll-feed